app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: ERNI-Academy

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  auth:
    keys:
      - secret: '958100d8c2655b7f002d3a5e537351f71b6b2b8fa4e36f2af66d9ec595d7233d61e8feff20e56be968b3b081cc97a052df73fa7dc4a9f5e876fc00e9d34c9e1d'
  csp:
    connect-src: ["'self'", 'http:', 'https:']

  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy:

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  providers:
    {}

scaffolder:

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: ../../examples/entities.yaml

    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]